# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eric/workspace/filesystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eric/workspace/filesystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eric/workspace/filesystem/CMakeFiles /home/eric/workspace/filesystem/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eric/workspace/filesystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ObjLib

# Build rule for target.
ObjLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ObjLib
.PHONY : ObjLib

# fast build rule for target.
ObjLib/fast:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/build
.PHONY : ObjLib/fast

#=============================================================================
# Target rules for targets named test_filesystem

# Build rule for target.
test_filesystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_filesystem
.PHONY : test_filesystem

# fast build rule for target.
test_filesystem/fast:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/build
.PHONY : test_filesystem/fast

src/filesystem/v2/directory_iterator.o: src/filesystem/v2/directory_iterator.cpp.o
.PHONY : src/filesystem/v2/directory_iterator.o

# target to build an object file
src/filesystem/v2/directory_iterator.cpp.o:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/directory_iterator.cpp.o
.PHONY : src/filesystem/v2/directory_iterator.cpp.o

src/filesystem/v2/directory_iterator.i: src/filesystem/v2/directory_iterator.cpp.i
.PHONY : src/filesystem/v2/directory_iterator.i

# target to preprocess a source file
src/filesystem/v2/directory_iterator.cpp.i:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/directory_iterator.cpp.i
.PHONY : src/filesystem/v2/directory_iterator.cpp.i

src/filesystem/v2/directory_iterator.s: src/filesystem/v2/directory_iterator.cpp.s
.PHONY : src/filesystem/v2/directory_iterator.s

# target to generate assembly for a file
src/filesystem/v2/directory_iterator.cpp.s:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/directory_iterator.cpp.s
.PHONY : src/filesystem/v2/directory_iterator.cpp.s

src/filesystem/v2/operations.o: src/filesystem/v2/operations.cpp.o
.PHONY : src/filesystem/v2/operations.o

# target to build an object file
src/filesystem/v2/operations.cpp.o:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/operations.cpp.o
.PHONY : src/filesystem/v2/operations.cpp.o

src/filesystem/v2/operations.i: src/filesystem/v2/operations.cpp.i
.PHONY : src/filesystem/v2/operations.i

# target to preprocess a source file
src/filesystem/v2/operations.cpp.i:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/operations.cpp.i
.PHONY : src/filesystem/v2/operations.cpp.i

src/filesystem/v2/operations.s: src/filesystem/v2/operations.cpp.s
.PHONY : src/filesystem/v2/operations.s

# target to generate assembly for a file
src/filesystem/v2/operations.cpp.s:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/operations.cpp.s
.PHONY : src/filesystem/v2/operations.cpp.s

src/filesystem/v2/path.o: src/filesystem/v2/path.cpp.o
.PHONY : src/filesystem/v2/path.o

# target to build an object file
src/filesystem/v2/path.cpp.o:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/path.cpp.o
.PHONY : src/filesystem/v2/path.cpp.o

src/filesystem/v2/path.i: src/filesystem/v2/path.cpp.i
.PHONY : src/filesystem/v2/path.i

# target to preprocess a source file
src/filesystem/v2/path.cpp.i:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/path.cpp.i
.PHONY : src/filesystem/v2/path.cpp.i

src/filesystem/v2/path.s: src/filesystem/v2/path.cpp.s
.PHONY : src/filesystem/v2/path.s

# target to generate assembly for a file
src/filesystem/v2/path.cpp.s:
	$(MAKE) -f CMakeFiles/ObjLib.dir/build.make CMakeFiles/ObjLib.dir/src/filesystem/v2/path.cpp.s
.PHONY : src/filesystem/v2/path.cpp.s

unit_tests/directory_entry_test.o: unit_tests/directory_entry_test.cpp.o
.PHONY : unit_tests/directory_entry_test.o

# target to build an object file
unit_tests/directory_entry_test.cpp.o:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/directory_entry_test.cpp.o
.PHONY : unit_tests/directory_entry_test.cpp.o

unit_tests/directory_entry_test.i: unit_tests/directory_entry_test.cpp.i
.PHONY : unit_tests/directory_entry_test.i

# target to preprocess a source file
unit_tests/directory_entry_test.cpp.i:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/directory_entry_test.cpp.i
.PHONY : unit_tests/directory_entry_test.cpp.i

unit_tests/directory_entry_test.s: unit_tests/directory_entry_test.cpp.s
.PHONY : unit_tests/directory_entry_test.s

# target to generate assembly for a file
unit_tests/directory_entry_test.cpp.s:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/directory_entry_test.cpp.s
.PHONY : unit_tests/directory_entry_test.cpp.s

unit_tests/file_status_test.o: unit_tests/file_status_test.cpp.o
.PHONY : unit_tests/file_status_test.o

# target to build an object file
unit_tests/file_status_test.cpp.o:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/file_status_test.cpp.o
.PHONY : unit_tests/file_status_test.cpp.o

unit_tests/file_status_test.i: unit_tests/file_status_test.cpp.i
.PHONY : unit_tests/file_status_test.i

# target to preprocess a source file
unit_tests/file_status_test.cpp.i:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/file_status_test.cpp.i
.PHONY : unit_tests/file_status_test.cpp.i

unit_tests/file_status_test.s: unit_tests/file_status_test.cpp.s
.PHONY : unit_tests/file_status_test.s

# target to generate assembly for a file
unit_tests/file_status_test.cpp.s:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/file_status_test.cpp.s
.PHONY : unit_tests/file_status_test.cpp.s

unit_tests/test_main.o: unit_tests/test_main.cpp.o
.PHONY : unit_tests/test_main.o

# target to build an object file
unit_tests/test_main.cpp.o:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/test_main.cpp.o
.PHONY : unit_tests/test_main.cpp.o

unit_tests/test_main.i: unit_tests/test_main.cpp.i
.PHONY : unit_tests/test_main.i

# target to preprocess a source file
unit_tests/test_main.cpp.i:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/test_main.cpp.i
.PHONY : unit_tests/test_main.cpp.i

unit_tests/test_main.s: unit_tests/test_main.cpp.s
.PHONY : unit_tests/test_main.s

# target to generate assembly for a file
unit_tests/test_main.cpp.s:
	$(MAKE) -f CMakeFiles/test_filesystem.dir/build.make CMakeFiles/test_filesystem.dir/unit_tests/test_main.cpp.s
.PHONY : unit_tests/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ObjLib"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_filesystem"
	@echo "... src/filesystem/v2/directory_iterator.o"
	@echo "... src/filesystem/v2/directory_iterator.i"
	@echo "... src/filesystem/v2/directory_iterator.s"
	@echo "... src/filesystem/v2/operations.o"
	@echo "... src/filesystem/v2/operations.i"
	@echo "... src/filesystem/v2/operations.s"
	@echo "... src/filesystem/v2/path.o"
	@echo "... src/filesystem/v2/path.i"
	@echo "... src/filesystem/v2/path.s"
	@echo "... unit_tests/directory_entry_test.o"
	@echo "... unit_tests/directory_entry_test.i"
	@echo "... unit_tests/directory_entry_test.s"
	@echo "... unit_tests/file_status_test.o"
	@echo "... unit_tests/file_status_test.i"
	@echo "... unit_tests/file_status_test.s"
	@echo "... unit_tests/test_main.o"
	@echo "... unit_tests/test_main.i"
	@echo "... unit_tests/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

